import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {ArticlePreview} from '../components';
import {getAllArticles} from '../lib/api';

export default function Home(props) {
  console.log('page props', props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the Wrapbook Engineering Blog Spike!
        </h1>

        <ul>
          {props.articles.map((article) => {
            return (
              <ArticlePreview key={article.slug} title={article.title} excerpt={article.excerpt} slug={article.slug} />
            )
          })}

        </ul>

      </main>
    </div>
  )
}

export function getStaticProps() {
  const articles = getAllArticles();

  return {
    props: {
      articles
    }
  }
}